targets:
  $default:
    sources:
      - lib/**
      - web/**
      - pubspec.yaml
      - lib/$lib$
      - $package$
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              version: "3.38"
              modules: [fts5]

      build_web_compilers:entrypoint:
        generate_for:
          - web/worker.dart
        options:
          compiler: dart2js

  copy_js:
    auto_apply_builders: false
    dependencies: [$default]
    builders:
      ":copy_compiled_worker_js":
        enabled: true

builders:
  copy_compiled_worker_js:
    import: "tool/builder.dart"
    builder_factories: ["CopyCompiledJs.new"]
    build_to: source
    build_extensions: { "web/worker.dart.js": ["web/drift_worker.js"] }
